{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logfire.serviceAccountName" . }}
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "logfire.fullname" . }}-pod-watcher
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "logfire.fullname" . }}-pod-watcher
  labels:
    {{- include "logfire.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "logfire.fullname" . }}-pod-watcher
subjects:
  - kind: ServiceAccount
    name: {{ include "logfire.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
